/* ********************** ITEM MASTER TABLE **************************/

DROP TABLE IF EXISTS ITMMAS;

CREATE TABLE ITMMAS
(	
	ITMITMNO		VARCHAR(30)	    NOT NULL,		-- ITEM CODE
	ITMNAM			VARCHAR(80)		NULL,	-- ITEM NAME
	ITMSPEC			VARCHAR(500)	NULL,	-- ITEM SPECIFIC
	ITMPICPTH		VARCHAR(200)    NULL,   -- ITEM PICTURE PATH
	
	ITMTYPE			VARCHAR(01)		NULL,	-- ITEM TYPE
	ITMORG			VARCHAR(01)		NULL,	-- ITEM ORGANS
	ITMSTATUS		VARCHAR(01)		NULL,   -- ITEM STATUS
	ITMCAGCD		VARCHAR(10)		NULL,	-- ITEM CATEGORY
	ITMDIVCD		VARCHAR(10)		NULL,   -- ITEM DIVISION
	ITMUOM			VARCHAR(04)		NULL,   -- ITEM UOM
	
	ITMCTYCD		VARCHAR(10)		NULL,	-- ITEM COUNTRY OF ORIGIN
	ITMQRCODE		VARCHAR(50)		NULL,	
	
	ITMRMK			VARCHAR(100)	NULL,	-- ITEM REMARK

	ITMNUTRTN		VARCHAR(100)	NULL,	-- ITEM NUTRITION
	ITMSIDEFF       VARCHAR(100)	NULL,
	
	ITMCOLOR		VARCHAR(100)	NULL,	-- ITEM REMARK
	ITMSIZE			VARCHAR(100)	NULL,	-- ITEM REMARK
	
	ITMSTPEFF		DATETIME		NULL,	-- STOP FLAG
	ITMCRTUSR		VARCHAR(15)		NULL,	-- CREATE USER
	ITMCRTDTE		DATETIME		NULL,	-- CREATE DATE
	ITMLUPUSR		VARCHAR(15)		NULL,	-- LAST UPDATE USER
	ITMLUPDTE		DATETIME		NULL,   -- LAST UPDATE DATE

	CONSTRAINT PK_ITMMAS PRIMARY KEY NONCLUSTERED (ITMITMNO)
)
;
