/* ********************** Item Master Table **************************/
IF EXISTS (SELECT * FROM sysobjects WHERE ID = object_id('dbo.ITMMAS'))
	DROP TABLE ITMMAS
GO

CREATE TABLE ITMMAS
(	
	ITMITMNO	NVARCHAR(30),			-- ITEM CODE
	ITMNAM		NVARCHAR(80)	NULL,	-- ITEM NAME
	ITMSPEC		NVARCHAR(MAX)	NULL,	-- ITEM SPECIFIC
	
	ITMTYPE		NVARCHAR(01)	NULL,	-- ITEM TYPE
	ITMSTATUS	NVARCHAR(01)	NULL,   -- ITEM STATUS
	ITMCAGCD	NVARCHAR(10)	NULL,	-- ITEM CATEGORY
	ITMDIVCD	NVARCHAR(10)	NULL,   -- ITEM DIVISION
	ITMUOM		NVARCHAR(04)	NULL,   -- ITEM UOM

	ITMCTYCD	nVarchar(10)	NULL,	-- ITEM COUNTRY OF ORIGIN
	ITMBARCOD	nVarchar(30)	NULL,	-- ITEM BARCODE
	ITMHSCODE	nVarchar(50)	NULL,	
	ITMMSTKLVL	Decimal(13,4)	NULL,
	ITMRMK		nVarchar(100)	NULL,	-- ITEM REMARK
	
	-- Packing information	
	ITMNETWGT	Decimal(15,6)	NULL,
	ITMPCKQTY	Decimal(13,4)	NULL,
	ITMGRSWGT	Decimal(15,6)	NULL,
	ITMMSRMT	nVarchar(30)	NULL,
	ITMMSRCBM	Decimal(15,6)	NULL,

	-- analaysis information	
	ITMITACD1	nVarChar(10)	NULL,
	ITMITACD2	nVarChar(10)	NULL,
	ITMITACD3	nVarChar(10)	NULL,
	ITMITACD4	nVarChar(10)	NULL,
	ITMITACD5	nVarChar(10)	NULL,
	ITMITACD6	nVarChar(10)	NULL,

	-- Standard Unit Cost information	
	ITMSTDCURR	nVarChar(03)	NULL,
	ITMSTDCOST	Decimal(15,6)	NULL,
	ITMNSTDCURR	nVarChar(03)	NULL,
	ITMNSTDCOST	Decimal(15,6)	NULL,
	ITMNEFFDTE	Datetime		NULL,
	
	ITMMSTPRC	Decimal(15,6)	NULL,
	ITMMSTCURR  NVARCHAR(03)	NULL, 
	ITMMSTDISC	Decimal(5,2)	NULL,


	-- new field
	ITMDIMENS	NVARCHAR(150)	NULL,
	ITMTEMPRNG	NVARCHAR(150)	NULL,
	ITMBRAND	NVARCHAR(150)	NULL,

	ITMSTPEFF	DateTime		NULL,
	ITMCRTUSR	nVarChar(15)	NULL,
	ITMCRTDTE	DateTimeOffset	NULL,
	ITMLUPUSR	nVarChar(15)	NULL,
	ITMLUPDTE	DateTimeOffset	NULL,
	ITMMEMO		nVarChar(Max)	NULL,		-- INTERNAL MEMO

	CONSTRAINT PK_ITMMAS PRIMARY KEY NONCLUSTERED (ITMITMNO)
)
ON SP4MST
GO
