DELETE FROM NUTMAS;
DELETE FROM NUTLANG;

SET @SEQ = 0;
SET @NUT = 0;
SET @NUTCD = '';

SET @SEQ = @SEQ + 1;
SET @NUT = @NUT + 1;
SET @NUTCD = LPAD(CONVERT(@NUT, CHAR), 4, '0');

INSERT INTO NUTMAS (NUTCD, ORNSEQ)
SELECT @NUTCD, @SEQ;

INSERT INTO NUTLANG (NUTLANG, NUTCD, NUTNAM, NUTSPEC, NUTIMG)
SELECT '1', @NUTCD, 'Protein', N'Protein', '';

INSERT INTO NUTLANG (NUTLANG, NUTCD, NUTNAM, NUTSPEC, NUTIMG)
SELECT '2', @NUTCD, N'蛋白質', N'蛋白質', '';

INSERT INTO NUTLANG (NUTLANG, NUTCD, NUTNAM, NUTSPEC, NUTIMG)
SELECT '3', @NUTCD, N'蛋白質', N'蛋白質', '';

/* **********************************************************/

SET @SEQ = @SEQ + 1;
SET @NUT = @NUT + 1;
SET @NUTCD = LPAD(CONVERT(@NUT, CHAR), 4, '0');

INSERT INTO NUTMAS (NUTCD, ORNSEQ)
SELECT @NUTCD, @SEQ;

INSERT INTO NUTLANG (NUTLANG, NUTCD, NUTNAM, NUTSPEC, NUTIMG)
SELECT '1', @NUTCD, 'Carbohydrate', N'Carbohydrate', '';

INSERT INTO NUTLANG (NUTLANG, NUTCD, NUTNAM, NUTSPEC, NUTIMG)
SELECT '2', @NUTCD, N'碳水化合物', N'碳水化合物', '';

INSERT INTO NUTLANG (NUTLANG, NUTCD, NUTNAM, NUTSPEC, NUTIMG)
SELECT '3', @NUTCD, N'碳水化合物', N'碳水化合物', '';

/* **********************************************************/

SET @SEQ = @SEQ + 1;
SET @NUT = @NUT + 1;
SET @NUTCD = LPAD(CONVERT(@NUT, CHAR), 4, '0');

INSERT INTO NUTMAS (NUTCD, ORNSEQ)
SELECT @NUTCD, @SEQ;

INSERT INTO NUTLANG (NUTLANG, NUTCD, NUTNAM, NUTSPEC, NUTIMG)
SELECT '1', @NUTCD, 'Total fat', N'Total fat', '';

INSERT INTO NUTLANG (NUTLANG, NUTCD, NUTNAM, NUTSPEC, NUTIMG)
SELECT '2', @NUTCD, N'總脂肪', N'總脂肪', '';

INSERT INTO NUTLANG (NUTLANG, NUTCD, NUTNAM, NUTSPEC, NUTIMG)
SELECT '3', @NUTCD, N'總脂肪', N'總脂肪', '';

