DELETE FROM ORNMAS;
DELETE FROM ORNLANG;

SET @SEQ = 0;
SET @ORN = 0;
SET @ORNCD = '';

SET @SEQ = @SEQ + 1;
SET @ORN = @ORN + 1;
SET @ORNCD = LPAD(CONVERT(@ORN, CHAR), 4, '0');

INSERT INTO ORNMAS (ORNCD, ORNSEQ)
SELECT @ORNCD, @SEQ;

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '1', @ORNCD, 'Brain', N'Brain', '';

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '2', @ORNCD, N'腦', N'腦', '';

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '3', @ORNCD, N'脑', N'脑', '';

/* **********************************************************/

SET @SEQ = @SEQ + 1;
SET @ORN = @ORN + 1;
SET @ORNCD = LPAD(CONVERT(@ORN, CHAR), 4, '0');

INSERT INTO ORNMAS (ORNCD, ORNSEQ)
SELECT @ORNCD, @SEQ;

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '1', @ORNCD, 'Eye', N'Eye', '';

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '2', @ORNCD, N'眼睛', N'眼睛', '';

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '3', @ORNCD, N'眼睛', N'眼睛', '';

/* **********************************************************/

SET @SEQ = @SEQ + 1;
SET @ORN = @ORN + 1;
SET @ORNCD = LPAD(CONVERT(@ORN, CHAR), 4, '0');

INSERT INTO ORNMAS (ORNCD, ORNSEQ)
SELECT @ORNCD, @SEQ;

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '1', @ORNCD, 'Ear', N'Ear', '';

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '2', @ORNCD, N'耳朵', N'耳朵', '';

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '3', @ORNCD, N'耳朵', N'耳朵', '';

/* **********************************************************/

SET @SEQ = @SEQ + 1;
SET @ORN = @ORN + 1;
SET @ORNCD = LPAD(CONVERT(@ORN, CHAR), 4, '0');

INSERT INTO ORNMAS (ORNCD, ORNSEQ)
SELECT @ORNCD, @SEQ;

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '1', @ORNCD, 'Nose', N'Nose', '';

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '2', @ORNCD, N'鼻子', N'鼻子', '';

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '3', @ORNCD, N'鼻子', N'鼻子', '';

/* **********************************************************/

SET @SEQ = @SEQ + 1;
SET @ORN = @ORN + 1;
SET @ORNCD = LPAD(CONVERT(@ORN, CHAR), 4, '0');

INSERT INTO ORNMAS (ORNCD, ORNSEQ)
SELECT @ORNCD, @SEQ;

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '1', @ORNCD, 'Heart', N'Heart', '';

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '2', @ORNCD, N'心臟', N'耳朵', '';

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '3', @ORNCD, N'心脏', N'心脏', '';

/* **********************************************************/

SET @SEQ = @SEQ + 1;
SET @ORN = @ORN + 1;
SET @ORNCD = LPAD(CONVERT(@ORN, CHAR), 4, '0');

INSERT INTO ORNMAS (ORNCD, ORNSEQ)
SELECT @ORNCD, @SEQ;

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '1', @ORNCD, 'Lung', N'Lung', '';

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '2', @ORNCD, N'肺', N'肺', '';

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '3', @ORNCD, N'肺', N'肺', '';
   
/* **********************************************************/

SET @SEQ = @SEQ + 1;
SET @ORN = @ORN + 1;
SET @ORNCD = LPAD(CONVERT(@ORN, CHAR), 4, '0');

INSERT INTO ORNMAS (ORNCD, ORNSEQ)
SELECT @ORNCD, @SEQ;

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '1', @ORNCD, 'Kidney', N'Kidney', '';

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '2', @ORNCD, N'腎臟', N'腎臟', '';

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '3', @ORNCD, N'肾脏', N'肾脏', '';

/* **********************************************************/

SET @SEQ = @SEQ + 1;
SET @ORN = @ORN + 1;
SET @ORNCD = LPAD(CONVERT(@ORN, CHAR), 4, '0');

INSERT INTO ORNMAS (ORNCD, ORNSEQ)
SELECT @ORNCD, @SEQ;

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '1', @ORNCD, 'Stomach', N'Stomach', '';

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '2', @ORNCD, N'胃', N'胃', '';

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '3', @ORNCD, N'胃', N'胃', '';
  
/* **********************************************************/

SET @SEQ = @SEQ + 1;
SET @ORN = @ORN + 1;
SET @ORNCD = LPAD(CONVERT(@ORN, CHAR), 4, '0');

INSERT INTO ORNMAS (ORNCD, ORNSEQ)
SELECT @ORNCD, @SEQ;

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '1', @ORNCD, 'Small intestine', N'Small intestine', '';

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '2', @ORNCD, N'小腸', N'小腸', '';

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '3', @ORNCD, N'小肠', N'小肠', '';	

/* **********************************************************/

SET @SEQ = @SEQ + 1;
SET @ORN = @ORN + 1;
SET @ORNCD = LPAD(CONVERT(@ORN, CHAR), 4, '0');

INSERT INTO ORNMAS (ORNCD, ORNSEQ)
SELECT @ORNCD, @SEQ;

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '1', @ORNCD, 'Large intestine', N'Large intestine', '';

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '2', @ORNCD, N'大腸', N'大腸', '';

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '3', @ORNCD, N'大肠', N'大肠', '';	

/* **********************************************************/

SET @SEQ = @SEQ + 1;
SET @ORN = @ORN + 1;
SET @ORNCD = LPAD(CONVERT(@ORN, CHAR), 4, '0');

INSERT INTO ORNMAS (ORNCD, ORNSEQ)
SELECT @ORNCD, @SEQ;

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '1', @ORNCD, 'Bladder', N'Bladder', '';

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '2', @ORNCD, N'膀胱', N'膀胱', '';

INSERT INTO ORNLANG (ORNLANG, ORNCD, ORNNAM, ORNSPEC, ORNIMG)
SELECT '3', @ORNCD, N'膀胱', N'膀胱', '';	










