DELETE FROM PGMSPC WHERE SPCPGMID = 'MT101'

DECLARE @SEQ INTEGER
SELECT @SEQ = 0

SELECT @SEQ = @SEQ + 1
INSERT INTO PGMSPC (SPCRECTYP, SPCSYSID, SPCPGMID, SPCSEQ, SPCFLDID, SPCENGDES, SPCTCHDES, SPCSCHDES, SPCJPNDES, SPCTBLNAM, SPCDSPFLG)
SELECT 'SCR', 'MST', 'MT101', @SEQ, 'SCRHDR', N'Exchange Rate Master Maintenance', N'', N'', N'', '', ''

SELECT @SEQ = @SEQ + 1
INSERT INTO PGMSPC (SPCRECTYP, SPCSYSID, SPCPGMID, SPCSEQ, SPCFLDID, SPCENGDES, SPCTCHDES, SPCSCHDES, SPCJPNDES, SPCTBLNAM, SPCDSPFLG)
SELECT 'SCR', 'MST', 'MT101', @SEQ, 'LBLDOCDTE', N'Date', N'', N'', N'', '', ''

-- TABLE DATAGRID
SELECT @SEQ = @SEQ + 1
INSERT INTO PGMSPC (SPCRECTYP, SPCSYSID, SPCPGMID, SPCSEQ, SPCFLDID, SPCENGDES, SPCTCHDES, SPCSCHDES, SPCJPNDES, SPCTBLNAM, SPCDSPFLG)
SELECT 'SCR', 'MST', 'MT101', @SEQ, 'TMPEXCROPT', N'Exchange Rate Option', N'', N'', N'', '', ''

SELECT @SEQ = @SEQ + 1
INSERT INTO PGMSPC (SPCRECTYP, SPCSYSID, SPCPGMID, SPCSEQ, SPCFLDID, SPCENGDES, SPCTCHDES, SPCSCHDES, SPCJPNDES, SPCTBLNAM, SPCDSPFLG)
SELECT 'SCR', 'MST', 'MT101', @SEQ, 'TMPCURR', N'Currency', N'', N'', N'', '', ''

SELECT @SEQ = @SEQ + 1
INSERT INTO PGMSPC (SPCRECTYP, SPCSYSID, SPCPGMID, SPCSEQ, SPCFLDID, SPCENGDES, SPCTCHDES, SPCSCHDES, SPCJPNDES, SPCTBLNAM, SPCDSPFLG)
SELECT 'SCR', 'MST', 'MT101', @SEQ, 'TMPDESC', N'Description', N'', N'', N'', '', ''

SELECT @SEQ = @SEQ + 1
INSERT INTO PGMSPC (SPCRECTYP, SPCSYSID, SPCPGMID, SPCSEQ, SPCFLDID, SPCENGDES, SPCTCHDES, SPCSCHDES, SPCJPNDES, SPCTBLNAM, SPCDSPFLG)
SELECT 'SCR', 'MST', 'MT101', @SEQ, 'TMPDOCDTE', N'Document Date', N'', N'', N'', '', ''

SELECT @SEQ = @SEQ + 1
INSERT INTO PGMSPC (SPCRECTYP, SPCSYSID, SPCPGMID, SPCSEQ, SPCFLDID, SPCENGDES, SPCTCHDES, SPCSCHDES, SPCJPNDES, SPCTBLNAM, SPCDSPFLG)
SELECT 'SCR', 'MST', 'MT101', @SEQ, 'TMPSELRATE', N'Selling Rate', N'', N'', N'', '', ''

SELECT @SEQ = @SEQ + 1
INSERT INTO PGMSPC (SPCRECTYP, SPCSYSID, SPCPGMID, SPCSEQ, SPCFLDID, SPCENGDES, SPCTCHDES, SPCSCHDES, SPCJPNDES, SPCTBLNAM, SPCDSPFLG)
SELECT 'SCR', 'MST', 'MT101', @SEQ, 'TMPPURRATE', N'Purchase Rate', N'', N'', N'', '', ''

SELECT @SEQ = @SEQ + 1
INSERT INTO PGMSPC (SPCRECTYP, SPCSYSID, SPCPGMID, SPCSEQ, SPCFLDID, SPCENGDES, SPCTCHDES, SPCSCHDES, SPCJPNDES, SPCTBLNAM, SPCDSPFLG)
SELECT 'SCR', 'MST', 'MT101', @SEQ, 'TMPGENRATE', N'General Rate', N'', N'', N'', '', ''

GO