/* ********************** ITEM LANGUAGE TABLE **************************/
DROP TABLE IF EXISTS ITMLANG;

CREATE TABLE ITMLANG
(	
	ITMLANG			VARCHAR(01),			-- LANGUAGE ID
	ITMITMNO		VARCHAR(30),			-- ITEM CODE
	ITMNAM			VARCHAR(80)		NULL,	-- ITEM NAME
	ITMSPEC			VARCHAR(500)	NULL,	-- ITEM SPECIFIC
	ITMPICPTH		VARCHAR(200)   	NULL,   -- ITEM PICTURE PATH
	ITMQRCODE		VARCHAR(50)		NULL,	-- ITEM QR CODE
	
	CONSTRAINT PK_ITMLANG PRIMARY KEY NONCLUSTERED (ITMITMNO, ITMLANG)
)