/* ********************** ORGANS LANGUAGE TABLE **************************/
DROP TABLE IF EXISTS ORNLANG;

CREATE TABLE ORNLANG
(	
	ORNLANG			VARCHAR(01),			-- LANGUAGE ID
	ORNCD			VARCHAR(30),			-- ORGANS CODE
	ORNNAM			VARCHAR(80)		NULL,	-- ORGANS NAME
	ORNSPEC			VARCHAR(500)	NULL,	-- ORGANS SPECIFIC
	ORNIMG			VARCHAR(500)	NULL,	-- ORGANS IMAGE
	
	CONSTRAINT PK_ORNLANG PRIMARY KEY NONCLUSTERED (ORNLANG, ORNCD)
)