/* ********************** ORNMAPPING MASTER TABLE **************************/
DROP TABLE IF EXISTS ORNMAPPING;

CREATE TABLE ORNMAPPING
(	
	ITMNO		VARCHAR(30),			-- ITEM CODE
	OGNCD		VARCHAR(01)		NULL,	-- ITEM ORGANS CODE

	CONSTRAINT PK_ORNMAPPING PRIMARY KEY NONCLUSTERED (ITMNO, OGNCD)
)